'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';

const SESSION_KEY='3on_admin_session_v2_staging',CACHE_KEY='3on_growth_staging_cache_v1';
const mutation=()=>crypto.randomUUID();
type Tab='growth'|'upload'|'review'|'changes'|'legacy';
type Overlay='review'|'confirm'|'publishSummary'|'publishConfirm'|'publishResult'|'withdrawConfirm'|null;
type PendingDecision={action:string;rowId:string;title:string;summary:string[];payload:Record<string,unknown>};

function token(){try{const x=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');return x&&x.expires>Date.now()?x.token:'';}catch{return'';}}
async function call(path:string,options:RequestInit={}):Promise<any>{const r=await fetch(path,{...options,cache:'no-store',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(token()?{Authorization:'Bearer '+token()}:{}),...options.headers}});const data:any=await r.json().catch(()=>({error:'응답을 읽지 못했습니다.'}));if(!r.ok)throw Object.assign(new Error(data.error||'요청을 완료하지 못했습니다.'),{status:r.status,data});return data;}
const fmt=(n:any)=>n==null?'—':Number(n).toLocaleString('ko-KR');
const done=(row:any)=>['resolved','new','unobserved'].includes(row.resolution_status);
const stateText=(state:string)=>({needs_review:'확인 진행 중',ready:'공개 준비 완료',published:'공개 완료',withdrawn:'공개 철회',superseded:'정정됨'} as Record<string,string>)[state]||state;
const actionText=(action:string,row?:any)=>({connect:'기존 인물 연결',direct_connect:'직접 수정',new:'신규 등록',direct_new:'신규 등록',unobserved:'이번 관측 미확인',hold:'보류',imported_decision:row?.resolution_status==='new'?'신규 등록':row?.resolution_status==='unobserved'?'이번 관측 미확인':row?.resolution_status==='held'?'보류':'사용자 확인'} as Record<string,string>)[action]||'변경';
const badgeText=(action:string,row?:any)=>({connect:'연결',direct_connect:'수정',new:'NEW',direct_new:'NEW',unobserved:'미확인',hold:'보류',imported_decision:row?.resolution_status==='new'?'NEW':row?.resolution_status==='unobserved'?'미확인':row?.resolution_status==='held'?'보류':'변경'} as Record<string,string>)[action]||'변경';

function Crop({url}:{url:string}){const [src,setSrc]=useState('');useEffect(()=>{let object='';fetch(url,{headers:{Authorization:'Bearer '+token()},cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.blob()}).then(b=>{object=URL.createObjectURL(b);setSrc(object)}).catch(()=>setSrc(''));return()=>{if(object)URL.revokeObjectURL(object)}},[url]);return src?<img className="crop" src={src} alt="판독 확인 부분"/>:<div className="crop emptyCrop">이미지 만료 또는 불러오기 실패</div>}

function Admin({admin,password,setPassword,login,logout,busy}:{admin:boolean;password:string;setPassword:(x:string)=>void;login:(e:React.FormEvent)=>void;logout:()=>void;busy:boolean}){return admin?<div className="adminOk"><div><b>Staging 관리자 인증됨</b><small>모든 저장은 Staging Draft에만 적용됩니다.</small></div><button onClick={logout}>로그아웃</button></div>:<form className="login" onSubmit={login}><label>Staging 관리자 비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button disabled={busy}>인증</button></form>}

function BatchStatus({review,current,onContinue,onChanges,onPublish}:{review:any;current:any;onContinue:()=>void;onChanges:()=>void;onPublish:()=>void}){
  if(!review)return null;const s=review.summary,b=review.batch;const published=b.state==='published';
  return <section className={'batchStatus '+(b.state==='ready'?'ready':published?'published':'draft')} aria-label="현재 성장자료 상태">
    <div className="batchStatusTitle"><div><span>{b.observed_date} 성장자료</span><h2>{published?'✅ 반영 완료':b.state==='ready'?'🟢 공개 준비 완료':'🟡 Draft 작성 중'}</h2></div><span className="stagePill">{published?'Published':'Draft'}</span></div>
    <div className="statusCounts"><div><b>{s.total}</b><span>전체</span></div><div><b>{s.automatic}</b><span>자동확정</span></div><div><b>{s.user_confirmed}</b><span>사용자확인</span></div><div><b>{s.review_required}</b><span>확인필요</span></div><div><b>{s.held}</b><span>보류</span></div></div>
    <p className="publicNow">현재 공개자료: {current?.observed_date||'—'} · revision {current?.revision??'—'}</p>
    <div className="statusActions">{!published&&s.review_required+s.held>0&&<button onClick={onContinue}>확인 계속하기</button>}<button className="secondary" onClick={onChanges}>변경 내역 보기</button>{b.state==='ready'&&<button className="success" onClick={onPublish}>최종 반영</button>}</div>
  </section>
}

function ReviewDetail({row,index,total,members,onClose,onMove,onDecision}:{row:any;index:number;total:number;members:any[];onClose:()=>void;onMove:(n:number)=>void;onDecision:(d:PendingDecision)=>void}){
  const initialId=row.resolved_member_id||row.candidate_member_id||'';
  const [memberId,setMemberId]=useState(initialId),[name,setName]=useState(row.proposed_display_name||row.candidate_name||row.raw_name),[power,setPower]=useState(String(row.power??'')),[level,setLevel]=useState(String(row.level??'')),[rank,setRank]=useState(row.rank||'R1');
  const member=members.find(m=>m.member_id===memberId);const payload={member_id:memberId,display_name:name.trim(),power:Number(power),level:Number(level),rank,confirm_alias:false};
  const ask=(action:string,title:string,summary:string[])=>onDecision({action,rowId:row.row_id,title,summary,payload});
  return <div className="overlay reviewOverlay" role="dialog" aria-modal="true" aria-labelledby="reviewTitle"><div className="sheet">
    <header className="sheetHead"><div><span className="progressText">확인 항목 {index+1} / {total}</span><h2 id="reviewTitle">{row.raw_name}</h2></div><button className="iconButton" onClick={onClose} aria-label="닫기">×</button></header>
    <div className="sheetBody">
      {row.asset_url&&<Crop url={row.asset_url}/>}<div className="detailGrid"><div><span>AI 판독</span><b>{row.raw_name}</b></div><div><span>기존 후보</span><b>{row.candidate_name||'없음'}</b></div><div><span>현재 표시명</span><b>{member?.display_name||row.member_display_name||'선택 전'}</b></div><div><span>legacy canonical</span><b>{member?.canonical||row.member_canonical||'없음'}</b></div><div><span>최근 등급</span><b>{member?.rank||'—'}</b></div><div><span>최근 레벨</span><b>{member?.level??'—'}</b></div><div><span>최근 전투력</span><b>{fmt(member?.power)}</b></div><div><span>확인 사유</span><b>{row.uncertainty_reason||'사용자 확인 또는 수정 항목'}</b></div></div>
      <label className="field">기존 길드원 검색·선택<select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">선택하세요</option>{members.map(m=><option key={m.member_id} value={m.member_id}>{m.display_name} · {m.canonical||'신규'} · Lv.{m.level}</option>)}</select></label>
      <div className="fields three"><label>등급<select value={rank} onChange={e=>setRank(e.target.value)}>{['R5','R4','R3','R2','R1'].map(x=><option key={x}>{x}</option>)}</select></label><label>레벨<input inputMode="numeric" value={level} onChange={e=>setLevel(e.target.value)}/></label><label>전투력<input inputMode="numeric" value={power} onChange={e=>setPower(e.target.value)}/></label></div>
      <label className="field">직접 입력·신규 닉네임<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label>
      <p className="draftExplain"><b>현재 단계: Draft</b><br/>아래 결정을 적용해도 최종 공개 전까지 성장 현황에는 반영되지 않습니다.</p>
    </div>
    <div className="decisionDock"><div className="decisionButtons"><button disabled={!memberId} onClick={()=>ask('connect','기존 인물로 연결',['AI 판독: '+row.raw_name,'처리: 기존 길드원 '+(member?.display_name||'선택 인물')+'과 연결','현재 단계: Draft'])}>기존 인물로 연결</button><button disabled={!memberId} onClick={()=>ask('direct_connect','직접 입력값 적용',['대상: '+(member?.display_name||'선택 인물'),'등급 '+rank+' · 레벨 '+level,'전투력 '+fmt(power),'현재 단계: Draft'])}>직접 입력</button><button disabled={!name.trim()} onClick={()=>ask('direct_new','신규 member 등록',['신규 표시명: '+name.trim(),'등급 '+rank+' · 레벨 '+level,'전투력 '+fmt(power),'현재 단계: Draft'])}>신규 인물 등록</button><button disabled={!memberId} onClick={()=>ask('unobserved','이번 관측 미확인 처리',['대상: '+(member?.display_name||'선택 인물'),'이번 관측 수치를 공개하지 않음','현재 단계: Draft'])}>이번 관측 미확인</button><button className="secondary full" onClick={()=>ask('hold','이 항목을 보류',['항목: '+row.raw_name,'확인 대기에 남겨 둠','현재 단계: Draft'])}>보류</button></div><div className="reviewNav"><button disabled={index===0} onClick={()=>onMove(index-1)}>이전</button><b>{index+1} / {total}</b><button disabled={index>=total-1} onClick={()=>onMove(index+1)}>다음</button></div></div>
  </div></div>
}

function ConfirmOverlay({decision,busy,onCancel,onApply}:{decision:PendingDecision;busy:boolean;onCancel:()=>void;onApply:()=>void}){return <div className="overlay confirmOverlay" role="alertdialog" aria-modal="true" aria-labelledby="confirmTitle"><div className="confirmCard"><span className="confirmIcon">✓?</span><h2 id="confirmTitle">변경 내용을 확인해 주세요</h2><h3>{decision.title}</h3><ul>{decision.summary.map((x,i)=><li key={i}>{x}</li>)}</ul><p>아직 공개 성장자료에는 반영되지 않습니다.</p><div className="confirmActions"><button className="secondary" disabled={busy} onClick={onCancel}>취소</button><button disabled={busy} onClick={onApply}>{busy?'저장 중…':'적용'}</button></div></div></div>}

function ChangeCard({item,onEdit,onReset,busy}:{item:any;onEdit:()=>void;onReset:()=>void;busy:boolean}){const row=item.row,d=item.decision;return <article className="changeCard"><div className="changeTop"><span className={'changeBadge '+badgeText(d.action,row)}>{badgeText(d.action,row)}</span><div><h3>{row.proposed_display_name||row.member_display_name||row.raw_name}</h3><p>{actionText(d.action,row)}</p></div></div><div className="changeCompare"><span>{row.raw_name}</span><b>→</b><span>{d.action==='connect'||d.action==='direct_connect'?row.member_display_name||'기존 member':row.proposed_display_name||stateText(row.resolution_status)}</span></div>{d.action==='direct_connect'&&<small>Power {fmt(d.before.power)} → {fmt(d.after.power)} · Lv.{d.before.level??'—'} → Lv.{d.after.level??'—'}</small>}<div className="cardActions"><button onClick={onEdit}>수정</button><button className="dangerGhost" disabled={busy} onClick={onReset}>변경 취소</button></div></article>}

export default function Home(){
  const [tab,setTabState]=useState<Tab>('growth'),[overlay,setOverlay]=useState<Overlay>(null),[selectedRowId,setSelectedRowId]=useState(''),[pending,setPending]=useState<PendingDecision|null>(null),[current,setCurrent]=useState<any>(null),[stale,setStale]=useState(false),[synced,setSynced]=useState(''),[admin,setAdmin]=useState(false),[password,setPassword]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[batchId,setBatchId]=useState(''),[review,setReview]=useState<any>(null),[batches,setBatches]=useState<any[]>([]),[snack,setSnack]=useState<any>(null),[showChanged,setShowChanged]=useState(false),[publishResult,setPublishResult]=useState<any>(null),[withdrawTarget,setWithdrawTarget]=useState<any>(null);
  const setTab=(next:Tab,push=true)=>{setOverlay(null);setSelectedRowId('');setTabState(next);if(push)history.pushState({tab:next},'',`#${next}`)};
  const loadCurrent=useCallback(async()=>{try{const x=await call('/api/growth/current');setCurrent(x);setStale(false);setSynced(new Date().toLocaleString('ko-KR'));localStorage.setItem(CACHE_KEY,JSON.stringify({savedAt:Date.now(),data:x}));}catch{try{const c=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(c?.data){setCurrent(c.data);setStale(true);setSynced(new Date(c.savedAt).toLocaleString('ko-KR'));}}catch{}}},[]);
  const verify=useCallback(async()=>{try{setAdmin(!!(await call('/api/session')).admin)}catch{setAdmin(false)}},[]);
  const loadReview=useCallback(async(id:string)=>{if(!id||!token())return null;try{const x=await call('/api/growth/review?batch_id='+encodeURIComponent(id));setReview(x);setBatchId(id);setNotice('');return x;}catch(e:any){setNotice(e.message);return null}},[]);
  const loadBatches=useCallback(async()=>{if(!token())return[];try{const list=(await call('/api/growth/batches')).batches;setBatches(list);return list}catch{return[]}},[]);
  useEffect(()=>{const hash=location.hash.slice(1) as Tab;const initial=(['growth','upload','review','changes','legacy'] as Tab[]).includes(hash)?hash:'growth';setTabState(initial);history.replaceState({tab:initial},'',location.hash||'#growth');const pop=(e:PopStateEvent)=>{setTabState(e.state?.tab||'growth');setOverlay(e.state?.overlay||null);setSelectedRowId(e.state?.rowId||'')};addEventListener('popstate',pop);loadCurrent();verify();return()=>removeEventListener('popstate',pop)},[loadCurrent,verify]);
  useEffect(()=>{if(!admin)return;loadBatches().then(list=>{const chosen=batchId||list.find((b:any)=>['needs_review','ready'].includes(b.state))?.batch_id||list[0]?.batch_id;if(chosen)loadReview(chosen)})},[admin,batchId,loadBatches,loadReview]);
  const ranks=useMemo(()=>current?Object.fromEntries(['R5','R4','R3','R2','R1'].map(r=>[r,current.members.filter((m:any)=>m.rank===r).length])):{},[current]);
  const reviewRows=useMemo(()=>review?.rows.filter((r:any)=>!done(r)||review.changes.some((c:any)=>c.row.row_id===r.row_id))||[],[review]);
  const selectedIndex=Math.max(0,reviewRows.findIndex((r:any)=>r.row_id===selectedRowId));const selectedRow=reviewRows[selectedIndex];
  const changeByMember=useMemo(()=>{const map=new Map<string,any>();for(const c of review?.changes||[]){const id=c.row.resolved_member_id||c.row.proposed_member_id;if(id)map.set(id,c)}return map},[review]);
  const previewMembers=useMemo(()=>{if(!current)return[];const base=current.members.map((m:any,i:number)=>({...m,_order:i,_change:changeByMember.get(m.member_id)||null}));for(const c of review?.changes||[])if(c.row.proposed_member_id&&!base.some((m:any)=>m.member_id===c.row.proposed_member_id))base.push({member_id:c.row.proposed_member_id,display_name:c.row.proposed_display_name,canonical:null,rank:c.row.rank,level:c.row.level,power:c.row.power,membership_state:'new',_order:9999,_change:c});if(admin&&review?.changes?.length)base.sort((a:any,b:any)=>Number(!!b._change)-Number(!!a._change)||a._order-b._order);return showChanged?base.filter((m:any)=>m._change):base},[current,review,changeByMember,admin,showChanged]);
  const openOverlay=(kind:Overlay,rowId='')=>{setOverlay(kind);if(rowId)setSelectedRowId(rowId);history.pushState({tab,overlay:kind,rowId:rowId||selectedRowId},'',`#${tab}`)};
  const closeOverlay=()=>history.back();
  const openRow=(id:string)=>openOverlay('review',id);
  const moveRow=(index:number)=>{const id=reviewRows[index]?.row_id;if(!id)return;setSelectedRowId(id);history.replaceState({tab,overlay:'review',rowId:id},'',`#${tab}`)};
  const requestDecision=(decision:PendingDecision)=>{setPending(decision);setOverlay('confirm');history.pushState({tab,overlay:'confirm',rowId:decision.rowId},'',`#${tab}`)};
  const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const x=await call('/api/session',{method:'POST',body:JSON.stringify({password})});sessionStorage.setItem(SESSION_KEY,JSON.stringify(x));setAdmin(true);setPassword('');setNotice('Staging 관리자 인증 완료');}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const logout=async()=>{try{await call('/api/session',{method:'POST',body:JSON.stringify({action:'logout'})})}catch{}sessionStorage.removeItem(SESSION_KEY);setAdmin(false);setReview(null);setNotice('로그아웃했습니다.')};
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);setNotice('파일을 검사하고 있습니다…');try{const x=await call('/api/growth/upload',{method:'POST',body:await f.text(),headers:{'Content-Type':'application/json'}});setBatchId(x.batch.batch_id);setNotice(x.duplicate?'이미 등록된 자료를 열었습니다.':'초안 생성 완료 — 아직 공개되지 않았습니다.');setTab('review');await loadReview(x.batch.batch_id);await loadBatches()}catch(e:any){setNotice(e.message)}finally{setBusy(false);e.target.value=''}};
  const applyDecision=async()=>{if(!pending||!review)return;setBusy(true);try{const x=await call('/api/growth/review',{method:'POST',body:JSON.stringify({batch_id:review.batch.batch_id,row_id:pending.rowId,draft_revision:review.batch.draft_revision,mutation:mutation(),action:pending.action,...pending.payload})});setReview(x);const row=x.rows.find((r:any)=>r.row_id===pending.rowId);setSnack({message:pending.action==='reset'?`${row.raw_name} → Draft 변경 취소`:`${row.raw_name} → ${actionText(pending.action,row)} 저장`,detail:'현재 Draft이며 아직 공개되지 않았습니다.',rowId:pending.rowId,eventId:x.result?.event_id});setNotice('');history.back()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const mutateDecision=async(action:'undo'|'reset',rowId:string,eventId?:string)=>{if(!review)return;setBusy(true);try{const x=await call('/api/growth/review',{method:'POST',body:JSON.stringify({batch_id:review.batch.batch_id,row_id:rowId,event_id:eventId,draft_revision:review.batch.draft_revision,mutation:mutation(),action})});setReview(x);setSnack({message:action==='undo'?'마지막 Draft 변경을 되돌렸습니다.':'이 항목의 Draft 결정을 취소했습니다.',detail:'공개자료는 변경되지 않았습니다.'})}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const acceptWarnings=async()=>{if(!review)return;setBusy(true);try{const x=await call('/api/growth/review',{method:'POST',body:JSON.stringify({batch_id:review.batch.batch_id,draft_revision:review.batch.draft_revision,mutation:mutation(),action:'accept_warnings'})});setReview(x);setSnack({message:'경고 확인을 Draft에 저장했습니다.',detail:'최종 공개 전까지 공개자료는 바뀌지 않습니다.'})}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const openPublish=()=>openOverlay('publishSummary');
  const publish=async()=>{if(!review)return;setBusy(true);try{const result=await call('/api/growth/publish',{method:'POST',body:JSON.stringify({batch_id:review.batch.batch_id,growth_revision:review.batch.base_growth_revision,identity_revision:review.batch.identity_revision,draft_revision:review.batch.draft_revision,mutation:mutation()})});setPublishResult({...result,summary:review.summary,observed_date:review.batch.observed_date});await loadCurrent();await loadBatches();await loadReview(review.batch.batch_id);setTabState('growth');setOverlay('publishResult');history.replaceState({tab:'growth',overlay:'publishResult'},'','#growth')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const withdraw=async()=>{if(!withdrawTarget||!current)return;setBusy(true);try{const result=await call('/api/growth/withdraw',{method:'POST',body:JSON.stringify({batch_id:withdrawTarget.batch_id,growth_revision:current.revision,identity_revision:current.identity_revision,mutation:mutation()})});await loadCurrent();await loadBatches();setNotice(`${withdrawTarget.observed_date} 공개자료를 철회했습니다. growth revision ${result.growth_revision}`);setOverlay(null);setWithdrawTarget(null);history.replaceState({tab:'changes'},'','#changes')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const goChanges=()=>setTab('changes');

  return <main><header><div className="brand"><b>3ON</b><span>차세대 Staging</span></div><h1>성장자료 관리자</h1><p>Production과 완전히 분리된 업로드·확인·공개 환경</p></header>
    <nav aria-label="관리자 주요 메뉴">{([['growth','성장 현황'],['upload','자료 업로드'],['review','확인 대기'],['changes','변경 내역']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}{id==='review'&&review?.summary?.review_required>0?<em>{review.summary.review_required}</em>:null}</button>)}</nav>
    {notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')} aria-label="알림 닫기">×</button></div>}
    <Admin admin={admin} password={password} setPassword={setPassword} login={login} logout={logout} busy={busy}/>
    {admin&&review&&<BatchStatus review={review} current={current} onContinue={()=>{setTabState('review');history.pushState({tab:'review'},'','#review');const row=review.rows.find((r:any)=>!done(r));if(row)setTimeout(()=>{setSelectedRowId(row.row_id);setOverlay('review');history.pushState({tab:'review',overlay:'review',rowId:row.row_id},'','#review')},0)}} onChanges={goChanges} onPublish={openPublish}/>}

    {tab==='growth'&&<section>{current?<><div className={'sync '+(stale?'stale':'')}><b>{stale?'마지막 승인 cache':'API 최신 승인 자료'}</b><span>관측 {current.observed_date} · revision {current.revision} · 동기화 {synced}</span></div>{admin&&review?.changes?.length>0&&<div className="previewTools"><b>관리자 변경 미리보기</b><button className={showChanged?'active':''} onClick={()=>setShowChanged(v=>!v)}>이번 변경만 보기 · {review.changes.length}명</button></div>}<div className="kpis"><div><span>현재 길드원</span><b>{current.members.length}명</b></div><div><span>Identity revision</span><b>{current.identity_revision}</b></div><div><span>등급 분포</span><b>{Object.entries(ranks).map(([k,v])=>`${k} ${String(v)}`).join(' / ')}</b></div></div><div className="memberGrid">{previewMembers.map((m:any)=><article key={m.member_id} className={m._change?'changedMember':''}>{m._change&&<span className="memberBadge">{badgeText(m._change.decision.action,m._change.row)}</span>}<span>{m.rank} · Lv.{m.level}</span><h3>{m.display_name}</h3><b>{fmt(m.power)}</b><small>{m.membership_state==='unobserved'?'이번 관측 미확인':m.canonical||'신규 member_id'}</small></article>)}</div></>:<div className="empty">성장 API와 cache를 모두 읽지 못했습니다.</div>}</section>}

    {tab==='upload'&&<section>{admin&&<div className="uploadBox"><h2>AI 성장자료 파일 업로드</h2><p>서버가 파일을 검사해 Draft를 만듭니다. 업로드만으로 공개자료는 바뀌지 않습니다.</p><label className="fileButton">파일 한 개 선택<input type="file" accept="application/json,.json" onChange={upload} disabled={busy}/></label><a href="/api/growth/package-template" target="_blank">package 형식 예시 보기</a></div>}</section>}

    {tab==='review'&&<section>{admin&&<><div className="batchList"><div><h2>확인할 성장자료</h2><p>항목을 누르면 현재 위치에서 전체 화면 확인창이 열립니다.</p></div>{batches.filter(b=>['needs_review','ready'].includes(b.state)).map(b=><button key={b.batch_id} className={b.batch_id===batchId?'selected':''} onClick={()=>loadReview(b.batch_id)}><b>{b.observed_date} · {b.slot}</b><span>{stateText(b.state)} · Draft {b.draft_revision}</span></button>)}</div>{review&&<><div className="reviewHead"><h2>{review.batch.observed_date} 확인 대기</h2><p>남은 확인 {review.summary.review_required} · 보류 {review.summary.held} · 처리 {review.summary.processed}/{review.summary.total}</p>{review.batch.validation.blocking?.length>0&&<button onClick={()=>requestDecision({action:'accept_warnings',rowId:'',title:'검증 경고 확인',summary:['미확인 인원 상태를 유지','현재 단계: Draft'],payload:{}})}>미확인 인원 유지하고 경고 확인</button>}</div><div className="reviewQueue">{review.rows.filter((r:any)=>!done(r)).map((r:any,i:number)=><button key={r.row_id} onClick={()=>openRow(r.row_id)}><span><b>{r.raw_name}</b><small>{r.uncertainty_reason||stateText(r.resolution_status)}</small></span><em>{i+1}</em></button>)}{review.rows.filter((r:any)=>!done(r)).length===0&&<div className="empty compact">모든 필수 항목을 처리했습니다. 변경 내역을 확인한 뒤 최종 반영하세요.</div>}</div></>}</>}</section>}

    {tab==='changes'&&<section>{admin&&review?<><div className="changesHead"><div><h2>{review.batch.observed_date} 변경 내역</h2><p><b>{review.batch.state==='published'?'공개 완료':'아직 공개 안 됨 · Draft'}</b></p></div><span>{review.changes.length}건</span></div><div className="changeList">{review.changes.map((item:any)=><ChangeCard key={item.row.row_id} item={item} busy={busy} onEdit={()=>openRow(item.row.row_id)} onReset={()=>requestDecision({action:'reset',rowId:item.row.row_id,title:'Draft 변경 취소',summary:[`항목: ${item.row.raw_name}`,`현재 결정: ${actionText(item.decision.action,item.row)}`,'원래 확인 대기 상태로 복원','공개자료는 변경되지 않음'],payload:{}})}/>)}{review.changes.length===0&&<div className="empty compact">사용자가 직접 결정한 변경이 없습니다.</div>}</div>{review.batch.state==='ready'&&<button className="publish" disabled={busy} onClick={openPublish}>변경 요약 확인 후 최종 반영</button>}{review.batch.state==='published'&&review.batch.published_revision>1&&<button className="withdraw" onClick={()=>{setWithdrawTarget(review.batch);openOverlay('withdrawConfirm')}}>공개 후 반영 취소(철회)</button>}</>:admin?<div className="empty">확인할 Draft를 선택해 주세요.</div>:null}</section>}

    <details className="toolsMenu" open={tab==='legacy'}><summary>Staging 관리·검증 도구</summary><div><h2>기존 운영 기능 회귀검증</h2><p>Staging DB/API에 연결된 기존 5개 탭 검증 화면입니다. 평상시 성장자료 운영 메뉴가 아니며 Production에는 반영되지 않습니다.</p><button onClick={()=>setTab('legacy')}>검증 도구 설명 보기</button><a href="/legacy.html">기존 5개 탭 열기</a></div></details>
    {tab==='legacy'&&<section className="legacyBox"><h2>Staging 기존 운영 기능 확인</h2><p>성장추적 · 협곡대전 1소대 · 마차관리 · 운영이력 · 관리설정 기능을 Staging 복제 DB에서 확인합니다.</p><strong>이 화면의 저장은 Staging DB에만 반영됩니다.</strong><a className="primaryLink" href="/legacy.html">Staging 기존 운영본 열기</a><a href="/api/state" target="_blank">Staging 3문서 읽기 확인</a></section>}

    {selectedRow&&['review','confirm'].includes(overlay||'')&&(
      <ReviewDetail key={selectedRow.row_id+'-'+selectedRow.review_version} row={selectedRow} index={selectedIndex} total={reviewRows.length} members={current?.members||[]} onClose={closeOverlay} onMove={moveRow} onDecision={requestDecision}/>
    )}
    {overlay==='confirm'&&pending&&<ConfirmOverlay decision={pending} busy={busy} onCancel={closeOverlay} onApply={pending.action==='accept_warnings'?async()=>{await acceptWarnings();history.back()}:applyDecision}/>}
    {overlay==='publishSummary'&&review&&<div className="overlay" role="dialog" aria-modal="true"><div className="confirmCard summaryCard"><h2>최종 반영 전 변경 요약</h2><h3>{review.batch.observed_date} 성장자료</h3><div className="summaryRows"><span>전체 member <b>{review.summary.total}</b></span><span>신규 <b>{review.summary.new_members}</b></span><span>기존 member 연결 <b>{review.summary.connections}</b></span><span>수치 직접수정 <b>{review.summary.direct_edits}</b></span><span>미확인 <b>{review.summary.unobserved}</b></span><span>보류 <b>{review.summary.held}</b></span></div><p>현재 공개: {current?.observed_date} revision {current?.revision}<br/>반영 후 예상: {review.batch.observed_date} revision {(current?.revision||0)+1}</p><div className="confirmActions"><button className="secondary" onClick={closeOverlay}>취소</button><button onClick={()=>{setOverlay('publishConfirm');history.replaceState({tab,overlay:'publishConfirm'},'',`#${tab}`)}}>최종 반영 확인</button></div></div></div>}
    {overlay==='publishConfirm'&&review&&<div className="overlay" role="alertdialog" aria-modal="true"><div className="confirmCard"><h2>이 성장자료를 최종 공개할까요?</h2><ul><li>관측일: {review.batch.observed_date}</li><li>처리 인원: {review.summary.total}명</li><li>확인 필요: {review.summary.review_required}명</li><li>보류: {review.summary.held}명</li></ul><p>공개 후 모든 사용자에게 새 성장자료가 표시됩니다.</p><div className="confirmActions"><button className="secondary" disabled={busy} onClick={closeOverlay}>취소</button><button disabled={busy||review.summary.review_required+review.summary.held>0} onClick={publish}>{busy?'공개 중…':'최종 공개'}</button></div></div></div>}
    {overlay==='publishResult'&&publishResult&&<div className="overlay" role="dialog" aria-modal="true"><div className="confirmCard resultCard"><span className="resultIcon">✓</span><h2>성장자료 반영 완료</h2><ul><li>관측일: {publishResult.observed_date}</li><li>growth revision: {publishResult.growth_revision}</li><li>처리: {publishResult.summary.total}명</li><li>신규: {publishResult.summary.new_members}</li><li>변경: {publishResult.summary.changed_members}</li></ul><div className="confirmActions"><button className="secondary" onClick={()=>{setOverlay(null);history.replaceState({tab:'changes'},'','#changes');setTabState('changes')}}>변경 결과 보기</button><button onClick={()=>{setOverlay(null);history.replaceState({tab:'growth'},'','#growth');setTabState('growth')}}>성장 현황 보기</button></div></div></div>}
    {overlay==='withdrawConfirm'&&withdrawTarget&&<div className="overlay" role="alertdialog" aria-modal="true"><div className="confirmCard"><h2>공개 후 반영 취소</h2><p><b>Draft 변경 취소가 아니라 이미 공개된 batch 철회입니다.</b></p><ul><li>철회 대상: {withdrawTarget.observed_date}</li><li>공개 revision: {withdrawTarget.published_revision}</li><li>철회 후 growth revision: {(current?.revision||0)+1}</li><li>이전 유효 공개자료로 복귀</li></ul><div className="confirmActions"><button className="secondary" disabled={busy} onClick={closeOverlay}>취소</button><button className="danger" disabled={busy} onClick={withdraw}>{busy?'철회 중…':'공개자료 철회'}</button></div></div></div>}
    {snack&&<div className="snackbar" role="status"><div><b>✅ {snack.message}</b><span>{snack.detail}</span></div><div>{snack.eventId&&<button disabled={busy} onClick={()=>mutateDecision('undo',snack.rowId,snack.eventId)}>되돌리기</button>}<button onClick={()=>{setSnack(null);setTab('changes')}}>변경 내역</button><button className="iconButton" onClick={()=>setSnack(null)} aria-label="메시지 닫기">×</button></div></div>}
  </main>
}
