'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
const SESSION_KEY='3on_admin_session_v2_staging',CACHE_KEY='3on_growth_staging_cache_v1';
const mutation=()=>crypto.randomUUID();type Tab='growth'|'upload'|'review'|'legacy';
function token(){try{const x=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');return x&&x.expires>Date.now()?x.token:'';}catch{return'';}}
async function call(path:string,options:RequestInit={}):Promise<any>{const r=await fetch(path,{...options,cache:'no-store',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(token()?{Authorization:'Bearer '+token()}:{}),...options.headers}});const data:any=await r.json().catch(()=>({error:'응답을 읽지 못했습니다.'}));if(!r.ok)throw Object.assign(new Error(data.error||'요청을 완료하지 못했습니다.'),{status:r.status,data});return data;}
const fmt=(n:any)=>n==null?'—':Number(n).toLocaleString('ko-KR');
function Crop({url}:{url:string}){const [src,setSrc]=useState('');useEffect(()=>{let object='';fetch(url,{headers:{Authorization:'Bearer '+token()},cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.blob()}).then(b=>{object=URL.createObjectURL(b);setSrc(object)}).catch(()=>setSrc(''));return()=>{if(object)URL.revokeObjectURL(object)}},[url]);return src?<img className="crop" src={src} alt="판독 확인 부분"/>:<div className="crop emptyCrop">이미지 만료 또는 불러오기 실패</div>}
function ReviewCard({row,members,onDone,draft}:{row:any;members:any[];onDone:()=>void;draft:number}){
  const [memberId,setMemberId]=useState(row.resolved_member_id||''),[name,setName]=useState(row.proposed_display_name||row.candidate_name||row.raw_name),[power,setPower]=useState(String(row.power??'')),[level,setLevel]=useState(String(row.level??'')),[rank,setRank]=useState(row.rank||'R1'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const act=async(action:string)=>{setBusy(true);setMessage('');try{await call('/api/growth/review',{method:'POST',body:JSON.stringify({batch_id:row.batch_id,row_id:row.row_id,draft_revision:draft,mutation:mutation(),action,member_id:memberId,display_name:name,power:Number(power),level:Number(level),rank,confirm_alias:false})});onDone();}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
  return <article className="reviewCard">{row.asset_url&&<Crop url={row.asset_url}/>}<div className="eyebrow">AI 원문</div><h3>{row.raw_name}</h3><p className="warnText">{row.uncertainty_reason||'사용자 확인 필요'}</p><div className="fields three"><label>등급<select value={rank} onChange={e=>setRank(e.target.value)}>{['R5','R4','R3','R2','R1'].map(x=><option key={x}>{x}</option>)}</select></label><label>레벨<input inputMode="numeric" value={level} onChange={e=>setLevel(e.target.value)}/></label><label>전투력<input inputMode="numeric" value={power} onChange={e=>setPower(e.target.value)}/></label></div><label>기존 길드원 검색·선택<select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">선택하세요</option>{members.map(m=><option key={m.member_id} value={m.member_id}>{m.display_name} · {m.canonical||'신규'} · Lv.{m.level}</option>)}</select></label><div className="actions"><button disabled={busy||!memberId} onClick={()=>act('connect')}>기존 인물로 연결</button><button disabled={busy||!memberId} onClick={()=>act('unobserved')} className="secondary">이번 관측 미확인</button></div><label>직접 입력·신규 닉네임<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><div className="actions"><button disabled={busy||!name.trim()} onClick={()=>act('direct_new')}>신규 인물 등록</button><button disabled={busy} onClick={()=>act('hold')} className="secondary">보류</button></div>{message&&<p className="error">{message}</p>}</article>
}
export default function Home(){
  const [tab,setTabState]=useState<Tab>('growth'),[current,setCurrent]=useState<any>(null),[stale,setStale]=useState(false),[synced,setSynced]=useState(''),[admin,setAdmin]=useState(false),[password,setPassword]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[batchId,setBatchId]=useState(''),[review,setReview]=useState<any>(null),[batches,setBatches]=useState<any[]>([]);
  const setTab=(next:Tab,push=true)=>{setTabState(next);if(push)history.pushState({tab:next},'',`#${next}`)};
  const loadCurrent=useCallback(async()=>{try{const x=await call('/api/growth/current');setCurrent(x);setStale(false);setSynced(new Date().toLocaleString('ko-KR'));localStorage.setItem(CACHE_KEY,JSON.stringify({savedAt:Date.now(),data:x}));}catch{try{const c=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(c?.data){setCurrent(c.data);setStale(true);setSynced(new Date(c.savedAt).toLocaleString('ko-KR'));}}catch{}}},[]);
  const verify=useCallback(async()=>{try{setAdmin(!!(await call('/api/session')).admin)}catch{setAdmin(false)}},[]);
  const loadReview=useCallback(async(id=batchId)=>{if(!id||!token())return;try{const x=await call('/api/growth/review?batch_id='+encodeURIComponent(id));setReview(x);setBatchId(id);setNotice('');}catch(e:any){setNotice(e.message)}},[batchId]);
  const loadBatches=useCallback(async()=>{if(!token())return;try{setBatches((await call('/api/growth/batches')).batches)}catch{}},[]);
  useEffect(()=>{const initial=(location.hash.slice(1) as Tab)||'growth';setTabState(['growth','upload','review','legacy'].includes(initial)?initial:'growth');history.replaceState({tab:initial},'',location.hash||'#growth');const pop=(e:PopStateEvent)=>setTabState(e.state?.tab||'growth');addEventListener('popstate',pop);loadCurrent();verify();return()=>removeEventListener('popstate',pop)},[loadCurrent,verify]);
  useEffect(()=>{if(admin){loadBatches();if(batchId)loadReview(batchId)}},[admin,batchId,loadBatches,loadReview]);
  const ranks=useMemo(()=>current?Object.fromEntries(['R5','R4','R3','R2','R1'].map(r=>[r,current.members.filter((m:any)=>m.rank===r).length])):{},[current]);
  const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const x=await call('/api/session',{method:'POST',body:JSON.stringify({password})});sessionStorage.setItem(SESSION_KEY,JSON.stringify(x));setAdmin(true);setPassword('');setNotice('Staging 관리자 인증 완료');}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const logout=async()=>{try{await call('/api/session',{method:'POST',body:JSON.stringify({action:'logout'})})}catch{}sessionStorage.removeItem(SESSION_KEY);setAdmin(false);setNotice('로그아웃했습니다.');};
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);setNotice('파일을 검사하고 있습니다…');try{const x=await call('/api/growth/upload',{method:'POST',body:await f.text(),headers:{'Content-Type':'application/json'}});setBatchId(x.batch.batch_id);setNotice(x.duplicate?'이미 등록된 자료를 열었습니다.':'초안 생성 완료');setTab('review');await loadReview(x.batch.batch_id);await loadBatches();}catch(e:any){setNotice(e.message)}finally{setBusy(false);e.target.value=''}};
  const publish=async()=>{if(!review)return;setBusy(true);try{await call('/api/growth/publish',{method:'POST',body:JSON.stringify({batch_id:review.batch.batch_id,growth_revision:review.batch.base_growth_revision,identity_revision:review.batch.identity_revision,draft_revision:review.batch.draft_revision,mutation:mutation()})});setNotice('성장 묶음을 원자적으로 공개했습니다.');setReview(null);await loadCurrent();await loadBatches();setTab('growth');}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const acceptWarnings=async()=>{if(!review)return;setBusy(true);try{await call('/api/growth/review',{method:'POST',body:JSON.stringify({batch_id:review.batch.batch_id,draft_revision:review.batch.draft_revision,mutation:mutation(),action:'accept_warnings'})});await loadReview(review.batch.batch_id);}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const withdraw=async(b:any)=>{if(!confirm(`${b.observed_date} 성장 묶음의 공개 효력을 철회할까요?`))return;try{await call('/api/growth/withdraw',{method:'POST',body:JSON.stringify({batch_id:b.batch_id,growth_revision:current.revision,identity_revision:current.identity_revision,mutation:mutation()})});await loadCurrent();await loadBatches();setNotice('해당 묶음을 철회했습니다.')}catch(e:any){setNotice(e.message)}};
  return <main><header><div className="brand"><b>3ON</b><span>차세대 Staging</span></div><h1>운영센터 성장자료 검증</h1><p>Production과 분리된 구현·migration·확인 환경</p></header><nav>{([['growth','성장 현황'],['upload','자료 업로드'],['review','확인 대기'],['legacy','기존 운영 검증']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{notice&&<div className="notice">{notice}</div>}
  {tab==='growth'&&<section>{current?<><div className={'sync '+(stale?'stale':'')}><b>{stale?'마지막 승인 cache':'API 최신 승인 자료'}</b><span>관측 {current.observed_date} · revision {current.revision} · 동기화 {synced}</span></div><div className="kpis"><div><span>현재 길드원</span><b>{current.members.length}명</b></div><div><span>Identity revision</span><b>{current.identity_revision}</b></div><div><span>등급 분포</span><b>{Object.entries(ranks).map(([k,v])=>`${k} ${String(v)}`).join(' / ')}</b></div></div><div className="memberGrid">{current.members.map((m:any)=><article key={m.member_id}><span>{m.rank} · Lv.{m.level}</span><h3>{m.display_name}</h3><b>{fmt(m.power)}</b><small>{m.membership_state==='unobserved'?'이번 관측 미확인':m.canonical||'신규 member_id'}</small></article>)}</div></>:<div className="empty">성장 API와 cache를 모두 읽지 못했습니다.</div>}</section>}
  {tab==='upload'&&<section><Admin admin={admin} password={password} setPassword={setPassword} login={login} logout={logout} busy={busy}/>{admin&&<div className="uploadBox"><h2>AI 성장자료 파일 업로드</h2><p>파일 내부 구조는 서버가 검사합니다. 확정 전에는 공개 자료가 바뀌지 않습니다.</p><label className="fileButton">파일 한 개 선택<input type="file" accept="application/json,.json" onChange={upload} disabled={busy}/></label><a href="/api/growth/package-template" target="_blank">package 형식 예시 보기</a></div>}</section>}
  {tab==='review'&&<section><Admin admin={admin} password={password} setPassword={setPassword} login={login} logout={logout} busy={busy}/>{admin&&<><div className="batchList"><h2>최근 묶음</h2>{batches.map(b=><button key={b.batch_id} onClick={()=>loadReview(b.batch_id)}><b>{b.observed_date} · {b.slot}</b><span>{b.state} · draft {b.draft_revision}</span></button>)}</div>{review&&<><div className="reviewHead"><h2>{review.batch.observed_date} 성장 기록</h2><p>상태 {review.batch.state} · 확인 필요 {review.rows.filter((r:any)=>!['resolved','new','unobserved'].includes(r.resolution_status)).length}건</p>{review.batch.validation.blocking?.length>0&&<button onClick={acceptWarnings}>미확인 인원 유지하고 경고 확인</button>}</div>{review.rows.filter((r:any)=>!['resolved','new','unobserved'].includes(r.resolution_status)).map((r:any)=><ReviewCard key={r.row_id} row={r} members={current?.members||[]} draft={review.batch.draft_revision} onDone={()=>loadReview(review.batch.batch_id)}/>)}{review.batch.state==='ready'&&<button className="publish" disabled={busy} onClick={publish}>전체 묶음 최종 공개</button>}</>}{batches.filter(b=>b.state==='published'&&b.published_revision>1).map(b=><button className="withdraw" key={'w'+b.batch_id} onClick={()=>withdraw(b)}>{b.observed_date} 공개 묶음 철회</button>)}</>}</section>}
  {tab==='legacy'&&<section><div className="legacyBox"><h2>기존 운영 기능 격리 검증</h2><p>Staging DB와 API만 연결된 기존 5개 탭 운영본입니다. Production DB에는 연결되지 않습니다.</p><a className="primaryLink" href="/legacy.html">Staging 기존 운영본 열기</a><a href="/api/state" target="_blank">Staging 3문서 읽기 확인</a></div></section>}</main>
}
function Admin({admin,password,setPassword,login,logout,busy}:{admin:boolean;password:string;setPassword:(x:string)=>void;login:(e:React.FormEvent)=>void;logout:()=>void;busy:boolean}){return admin?<div className="adminOk"><b>Staging 관리자 인증됨</b><button onClick={logout}>로그아웃</button></div>:<form className="login" onSubmit={login}><label>Staging 관리자 비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button disabled={busy}>인증</button></form>}
